name: 'Get Latest (Stable) Tag'
description: 'Get the latest tag from git and outputs that for use in other actions'
branding:
  icon: 'tag'
  color: 'gray-dark'
inputs:
  fallback:
    description: 'Fallback tag to use when no previous tag can be found'
    required: false
  prefix:
    description: 'Prefix to query the tag by'
    required: false
  stable:
    description: 'Flag to determine whether to return stable tag'
    required: false
    type: boolean
  sort:
    description: 'Get the latest tag by date or by lexicograhical order'
    required: false
outputs:
  tag:
    description: 'Latest tag'
  timestamp:
    description: 'Latest tag timestamp'
runs:
  using: 'node16'
  main: 'main.js'
